/* S -> T */

CREATE TABLE transducer._CTP_INSERT AS
SELECT * FROM transducer._CTP
WHERE 1<>1;

CREATE TABLE transducer._CTP_DELETE AS
SELECT * FROM transducer._CTP
WHERE 1<>1;



CREATE TABLE transducer._CTP_INSERT_JOIN  AS
SELECT * FROM transducer._CTP
WHERE 1<>1;

CREATE TABLE transducer._CTP_DELETE_JOIN AS
SELECT * FROM transducer._CTP
WHERE 1<>1;


/** INSERT T -> S **/

CREATE TABLE transducer._CLIENT_INSERT AS
SELECT * FROM transducer._CLIENT
WHERE 1<>1;

CREATE TABLE transducer._CLIENT_DELETE AS
SELECT * FROM transducer._CLIENT
WHERE 1<>1;

CREATE TABLE transducer._TRANSACTION_INSERT AS
SELECT * FROM transducer._TRANSACTION
WHERE 1<>1;

CREATE TABLE transducer._TRANSACTION_DELETE AS
SELECT * FROM transducer._TRANSACTION
WHERE 1<>1;

CREATE TABLE transducer._PRODUCT_INSERT AS
SELECT * FROM transducer._PRODUCT
WHERE 1<>1;

CREATE TABLE transducer._PRODUCT_DELETE AS
SELECT * FROM transducer._PRODUCT
WHERE 1<>1;


CREATE TABLE transducer._CLIENT_INSERT_JOIN AS
SELECT * FROM transducer._CLIENT
WHERE 1<>1;

CREATE TABLE transducer._CLIENT_DELETE_JOIN AS
SELECT * FROM transducer._CLIENT
WHERE 1<>1;

CREATE TABLE transducer._TRANSACTION_INSERT_JOIN AS
SELECT * FROM transducer._TRANSACTION
WHERE 1<>1;

CREATE TABLE transducer._TRANSACTION_DELETE_JOIN AS
SELECT * FROM transducer._TRANSACTION
WHERE 1<>1;

CREATE TABLE transducer._PRODUCT_INSERT_JOIN AS
SELECT * FROM transducer._PRODUCT
WHERE 1<>1;

CREATE TABLE transducer._PRODUCT_DELETE_JOIN AS
SELECT * FROM transducer._PRODUCT
WHERE 1<>1;


CREATE TABLE transducer._LOOP (
loop_start INT NOT NULL );


CREATE TABLE transducer._SWITCH (
update_type INT NOT NULL );
