/** S->T INSERT TRIGGERS **/

CREATE TRIGGER source_SPERSON_INSERT_trigger
AFTER INSERT ON transducer._SPERSON
FOR EACH ROW
EXECUTE FUNCTION transducer.source_SPERSON_INSERT_fn();

CREATE TRIGGER source_SCITY_INSERT_trigger
AFTER INSERT ON transducer._SCITY
FOR EACH ROW
EXECUTE FUNCTION transducer.source_SCITY_INSERT_fn();


CREATE TRIGGER source_SPERSON_INSERT_JOIN_trigger
AFTER INSERT ON transducer._SPERSON_INSERT
FOR EACH ROW
EXECUTE FUNCTION transducer.source_SPERSON_INSERT_JOIN_fn();

CREATE TRIGGER source_SCITY_INSERT_JOIN_trigger
AFTER INSERT ON transducer._SCITY_INSERT
FOR EACH ROW
EXECUTE FUNCTION transducer.source_SCITY_INSERT_JOIN_fn();


CREATE TRIGGER source_INSERT_trigger_1
AFTER INSERT ON transducer._SPERSON_INSERT_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.source_INSERT_fn();

CREATE TRIGGER source_INSERT_trigger_2
AFTER INSERT ON transducer._SCITY_INSERT_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.source_INSERT_fn();


/** S->T DELETE TRIGGERS **/

CREATE TRIGGER source_SPERSON_DELETE_trigger
AFTER DELETE ON transducer._SPERSON
FOR EACH ROW
EXECUTE FUNCTION transducer.source_SPERSON_DELETE_fn();

CREATE TRIGGER source_SCITY_DELETE_trigger
AFTER DELETE ON transducer._SCITY
FOR EACH ROW
EXECUTE FUNCTION transducer.source_SCITY_DELETE_fn();


CREATE TRIGGER source_SPERSON_DELETE_JOIN_trigger
AFTER INSERT ON transducer._SPERSON_DELETE
FOR EACH ROW
EXECUTE FUNCTION transducer.source_SPERSON_DELETE_JOIN_fn();

CREATE TRIGGER source_SCITY_DELETE_JOIN_trigger
AFTER INSERT ON transducer._SCITY_DELETE
FOR EACH ROW
EXECUTE FUNCTION transducer.source_SCITY_DELETE_JOIN_fn();


CREATE TRIGGER source_DELETE_trigger_1
AFTER INSERT ON transducer._SPERSON_DELETE_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.source_DELETE_fn();

CREATE TRIGGER source_DELETE_trigger_2
AFTER INSERT ON transducer._SCITY_DELETE_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.source_DELETE_fn();



/** T->S INSERT **/

CREATE TRIGGER target_TPERSON_INSERT_trigger
AFTER INSERT ON transducer._TPERSON
FOR EACH ROW
EXECUTE FUNCTION transducer.target_TPERSON_INSERT_fn();

CREATE TRIGGER target_PERSON_PHONE_INSERT_trigger
AFTER INSERT ON transducer._PERSON_PHONE
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PERSON_PHONE_INSERT_fn();

CREATE TRIGGER target_PERSON_EMAIL_INSERT_trigger
AFTER INSERT ON transducer._PERSON_EMAIL
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PERSON_EMAIL_INSERT_fn();

CREATE TRIGGER target_TCITY_INSERT_trigger
AFTER INSERT ON transducer._TCITY
FOR EACH ROW
EXECUTE FUNCTION transducer.target_TCITY_INSERT_fn();

CREATE TRIGGER target_CITY_COORD_INSERT_trigger
AFTER INSERT ON transducer._CITY_COORD
FOR EACH ROW
EXECUTE FUNCTION transducer.target_CITY_COORD_INSERT_fn();


CREATE TRIGGER target_TPERSON_INSERT_JOIN_trigger
AFTER INSERT ON transducer._TPERSON_INSERT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_TPERSON_INSERT_JOIN_fn();

CREATE TRIGGER target_PERSON_PHONE_INSERT_JOIN_trigger
AFTER INSERT ON transducer._PERSON_PHONE_INSERT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PERSON_PHONE_INSERT_JOIN_fn();

CREATE TRIGGER target_PERSON_EMAIL_INSERT_JOIN_trigger
AFTER INSERT ON transducer._PERSON_EMAIL_INSERT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PERSON_EMAIL_INSERT_JOIN_fn();

CREATE TRIGGER target_TCITY_INSERT_JOIN_trigger
AFTER INSERT ON transducer._TCITY_INSERT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_TCITY_INSERT_JOIN_fn();

CREATE TRIGGER target_CITY_COORD_INSERT_JOIN_trigger
AFTER INSERT ON transducer._CITY_COORD_INSERT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_CITY_COORD_INSERT_JOIN_fn();


CREATE TRIGGER target_INSERT_trigger_1
AFTER INSERT ON transducer._TPERSON_INSERT_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_INSERT_fn();

CREATE TRIGGER target_INSERT_trigger_2
AFTER INSERT ON transducer._PERSON_PHONE_INSERT_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_INSERT_fn();

CREATE TRIGGER target_INSERT_trigger_3
AFTER INSERT ON transducer._PERSON_EMAIL_INSERT_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_INSERT_fn();

CREATE TRIGGER target_INSERT_trigger_4
AFTER INSERT ON transducer._TCITY_INSERT_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_INSERT_fn();

CREATE TRIGGER target_INSERT_trigger_5
AFTER INSERT ON transducer._CITY_COORD_INSERT_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_INSERT_fn();

/** T->S DELETE **/

CREATE TRIGGER target_TPERSON_DELETE_trigger
AFTER DELETE ON transducer._TPERSON
FOR EACH ROW
EXECUTE FUNCTION transducer.target_TPERSON_DELETE_fn();

CREATE TRIGGER target_PERSON_PHONE_DELETE_trigger
AFTER DELETE ON transducer._PERSON_PHONE
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PERSON_PHONE_DELETE_fn();

CREATE TRIGGER target_PERSON_EMAIL_DELETE_trigger
AFTER DELETE ON transducer._PERSON_EMAIL
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PERSON_EMAIL_DELETE_fn();

CREATE TRIGGER target_TCITY_DELETE_trigger
AFTER DELETE ON transducer._TCITY
FOR EACH ROW
EXECUTE FUNCTION transducer.target_TCITY_DELETE_fn();

CREATE TRIGGER target_CITY_COORD_DELETE_trigger
AFTER DELETE ON transducer._CITY_COORD
FOR EACH ROW
EXECUTE FUNCTION transducer.target_CITY_COORD_DELETE_fn();


CREATE TRIGGER target_TPERSON_DELETE_JOIN_trigger
AFTER INSERT ON transducer._TPERSON_DELETE
FOR EACH ROW
EXECUTE FUNCTION transducer.target_TPERSON_DELETE_JOIN_fn();

CREATE TRIGGER target_PERSON_PHONE_DELETE_JOIN_trigger
AFTER INSERT ON transducer._PERSON_PHONE_DELETE
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PERSON_PHONE_DELETE_JOIN_fn();

CREATE TRIGGER target_PERSON_EMAIL_DELETE_JOIN_trigger
AFTER INSERT ON transducer._PERSON_EMAIL_DELETE
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PERSON_EMAIL_DELETE_JOIN_fn();

CREATE TRIGGER target_TCITY_DELETE_JOIN_trigger
AFTER INSERT ON transducer._TCITY_DELETE
FOR EACH ROW
EXECUTE FUNCTION transducer.target_TCITY_DELETE_JOIN_fn();

CREATE TRIGGER target_CITY_COORD_DELETE_JOIN_trigger
AFTER INSERT ON transducer._CITY_COORD_DELETE
FOR EACH ROW
EXECUTE FUNCTION transducer.target_CITY_COORD_DELETE_JOIN_fn();


CREATE TRIGGER target_DELETE_trigger_1
AFTER INSERT ON transducer._TPERSON_DELETE_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_DELETE_fn();

CREATE TRIGGER target_DELETE_trigger_2
AFTER INSERT ON transducer._PERSON_PHONE_DELETE_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_DELETE_fn();

CREATE TRIGGER target_DELETE_trigger_3
AFTER INSERT ON transducer._PERSON_EMAIL_DELETE_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_DELETE_fn();

CREATE TRIGGER target_DELETE_trigger_4
AFTER INSERT ON transducer._TCITY_DELETE_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_DELETE_fn();

CREATE TRIGGER target_DELETE_trigger_5
AFTER INSERT ON transducer._CITY_COORD_DELETE_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_DELETE_fn();