/** S->T INSERT TRIGGERS **/

CREATE TRIGGER source_CTP_INSERT_trigger
AFTER INSERT ON transducer._CTP
FOR EACH ROW
EXECUTE FUNCTION transducer.source_CTP_INSERT_fn();


CREATE TRIGGER source_CTP_INSERT_JOIN_trigger
AFTER INSERT ON transducer._CTP_INSERT
FOR EACH ROW
EXECUTE FUNCTION transducer.source_CTP_INSERT_JOIN_fn();


CREATE TRIGGER source_INSERT_trigger_1
AFTER INSERT ON transducer._CTP_INSERT_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.source_INSERT_fn();


/** S->T DELETE TRIGGERS **/

CREATE TRIGGER source_CTP_DELETE_trigger
AFTER DELETE ON transducer._CTP
FOR EACH ROW
EXECUTE FUNCTION transducer.source_CTP_DELETE_fn();


CREATE TRIGGER source_CTP_DELETE_JOIN_trigger
AFTER INSERT ON transducer._CTP_DELETE
FOR EACH ROW
EXECUTE FUNCTION transducer.source_CTP_DELETE_JOIN_fn();
END;

CREATE TRIGGER source_DELETE_trigger_1
AFTER INSERT ON transducer._CTP_DELETE_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.source_DELETE_fn();


/** T->S INSERT **/

CREATE TRIGGER target_CLIENT_INSERT_trigger
AFTER INSERT ON transducer._CLIENT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_CLIENT_INSERT_fn();

CREATE TRIGGER target_TRANSACTION_INSERT_trigger
AFTER INSERT ON transducer._TRANSACTION
FOR EACH ROW
EXECUTE FUNCTION transducer.target_TRANSACTION_INSERT_fn();

CREATE TRIGGER target_PRODUCT_INSERT_trigger
AFTER INSERT ON transducer._PRODUCT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PRODUCT_INSERT_fn();



CREATE TRIGGER target_CLIENT_INSERT_JOIN_trigger
AFTER INSERT ON transducer._CLIENT_INSERT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_CLIENT_INSERT_JOIN_fn();

CREATE TRIGGER target_TRANSACTION_INSERT_JOIN_trigger
AFTER INSERT ON transducer._TRANSACTION_INSERT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_TRANSACTION_INSERT_JOIN_fn();

CREATE TRIGGER target_PRODUCT_INSERT_JOIN_trigger
AFTER INSERT ON transducer._PRODUCT_INSERT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PRODUCT_INSERT_JOIN_fn();


CREATE TRIGGER target_INSERT_trigger_1
AFTER INSERT ON transducer._CLIENT_INSERT_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_INSERT_fn();

CREATE TRIGGER target_INSERT_trigger_2
AFTER INSERT ON transducer._TRANSACTION_INSERT_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_INSERT_fn();

CREATE TRIGGER target_INSERT_trigger_4
AFTER INSERT ON transducer._PRODUCT_INSERT_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_INSERT_fn();


/** T->S DELETE **/

CREATE TRIGGER target_CLIENT_DELETE_trigger
AFTER DELETE ON transducer._CLIENT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_CLIENT_DELETE_fn();

CREATE TRIGGER target_TRANSACTION_DELETE_trigger
AFTER DELETE ON transducer._TRANSACTION
FOR EACH ROW
EXECUTE FUNCTION transducer.target_TRANSACTION_DELETE_fn();

CREATE TRIGGER target_PRODUCT_DELETE_trigger
AFTER DELETE ON transducer._PRODUCT
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PRODUCT_DELETE_fn();



CREATE TRIGGER target_CLIENT_DELETE_JOIN_trigger
AFTER INSERT ON transducer._CLIENT_DELETE
FOR EACH ROW
EXECUTE FUNCTION transducer.target_CLIENT_DELETE_JOIN_fn();

CREATE TRIGGER target_TRANSACTION_DELETE_JOIN_trigger
AFTER INSERT ON transducer._TRANSACTION_DELETE
FOR EACH ROW
EXECUTE FUNCTION transducer.target_TRANSACTION_DELETE_JOIN_fn();

CREATE TRIGGER target_PRODUCT_DELETE_JOIN_trigger
AFTER INSERT ON transducer._PRODUCT_DELETE
FOR EACH ROW
EXECUTE FUNCTION transducer.target_PRODUCT_DELETE_JOIN_fn();



CREATE TRIGGER target_DELETE_trigger_1
AFTER INSERT ON transducer._CLIENT_DELETE_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_DELETE_fn();

CREATE TRIGGER target_DELETE_trigger_2
AFTER INSERT ON transducer._TRANSACTION_DELETE_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_DELETE_fn();

CREATE TRIGGER target_DELETE_trigger_4
AFTER INSERT ON transducer._PRODUCT_DELETE_JOIN
FOR EACH ROW
EXECUTE FUNCTION transducer.target_DELETE_fn();

