/* S -> T */

CREATE TABLE transducer._SPERSON_INSERT AS
SELECT * FROM transducer._SPERSON
WHERE 1<>1;

CREATE TABLE transducer._SCITY_INSERT AS
SELECT * FROM transducer._SCITY
WHERE 1<>1;

CREATE TABLE transducer._SPERSON_DELETE AS
SELECT * FROM transducer._SPERSON
WHERE 1<>1;

CREATE TABLE transducer._SCITY_DELETE AS
SELECT * FROM transducer._SCITY
WHERE 1<>1;


CREATE TABLE transducer._SPERSON_INSERT_JOIN AS
SELECT * FROM transducer._SPERSON
WHERE 1<>1;

CREATE TABLE transducer._SCITY_INSERT_JOIN AS
SELECT * FROM transducer._SCITY
WHERE 1<>1;

CREATE TABLE transducer._SPERSON_DELETE_JOIN AS
SELECT * FROM transducer._SPERSON
WHERE 1<>1;

CREATE TABLE transducer._SCITY_DELETE_JOIN AS
SELECT * FROM transducer._SCITY
WHERE 1<>1;




/** INSERT T -> S **/

CREATE TABLE transducer._TPERSON_INSERT AS
SELECT * FROM transducer._TPERSON
WHERE 1<>1;

CREATE TABLE transducer._TPERSON_DELETE AS
SELECT * FROM transducer._TPERSON
WHERE 1<>1;

CREATE TABLE transducer._PERSON_PHONE_INSERT AS
SELECT * FROM transducer._PERSON_PHONE
WHERE 1<>1;

CREATE TABLE transducer._PERSON_PHONE_DELETE AS
SELECT * FROM transducer._PERSON_PHONE
WHERE 1<>1;

CREATE TABLE transducer._PERSON_EMAIL_INSERT AS
SELECT * FROM transducer._PERSON_EMAIL
WHERE 1<>1;

CREATE TABLE transducer._PERSON_EMAIL_DELETE AS
SELECT * FROM transducer._PERSON_EMAIL
WHERE 1<>1;

CREATE TABLE transducer._TCITY_INSERT AS
SELECT * FROM transducer._TCITY
WHERE 1<>1;

CREATE TABLE transducer._TCITY_DELETE AS
SELECT * FROM transducer._TCITY
WHERE 1<>1;

CREATE TABLE transducer._CITY_COORD_INSERT AS
SELECT * FROM transducer._CITY_COORD
WHERE 1<>1;

CREATE TABLE transducer._CITY_COORD_DELETE AS
SELECT * FROM transducer._CITY_COORD
WHERE 1<>1;



CREATE TABLE transducer._TPERSON_INSERT_JOIN AS
SELECT * FROM transducer._TPERSON
WHERE 1<>1;

CREATE TABLE transducer._TPERSON_DELETE_JOIN AS
SELECT * FROM transducer._TPERSON
WHERE 1<>1;

CREATE TABLE transducer._PERSON_PHONE_INSERT_JOIN AS
SELECT * FROM transducer._PERSON_PHONE
WHERE 1<>1;

CREATE TABLE transducer._PERSON_PHONE_DELETE_JOIN AS
SELECT * FROM transducer._PERSON_PHONE
WHERE 1<>1;

CREATE TABLE transducer._PERSON_EMAIL_INSERT_JOIN AS
SELECT * FROM transducer._PERSON_EMAIL
WHERE 1<>1;

CREATE TABLE transducer._PERSON_EMAIL_DELETE_JOIN AS
SELECT * FROM transducer._PERSON_EMAIL
WHERE 1<>1;

CREATE TABLE transducer._TCITY_INSERT_JOIN AS
SELECT * FROM transducer._TCITY
WHERE 1<>1;

CREATE TABLE transducer._TCITY_DELETE_JOIN AS
SELECT * FROM transducer._TCITY
WHERE 1<>1;

CREATE TABLE transducer._CITY_COORD_INSERT_JOIN AS
SELECT * FROM transducer._CITY_COORD
WHERE 1<>1;

CREATE TABLE transducer._CITY_COORD_DELETE_JOIN AS
SELECT * FROM transducer._CITY_COORD
WHERE 1<>1;


CREATE TABLE transducer._LOOP (
loop_start INT NOT NULL );